import { useLocale } from './LocaleContext.jsx'

const copy = {
  vi: {
    headerTitle: 'Báo cáo nghiên cứu RBL', headerDescription: 'So sánh chất lượng, độ bám nguồn và tốc độ phản hồi giữa RAG và Fine-tuned.',
    dataset: 'Bộ dữ liệu', ragRun: 'Lần chạy RAG', fineRun: 'Lần chạy Fine-tuned', selectDataset: 'Chọn bộ dữ liệu', selectRag: 'Chọn lần chạy RAG', selectFine: 'Chọn lần chạy Fine-tuned', noDatasets: 'Chưa có bộ dữ liệu', noRag: 'Chưa có lần chạy RAG', noFine: 'Chưa có lần chạy Fine-tuned',
    preparingReport: 'Đang chuẩn bị báo cáo...', preparingCharts: 'Đang chuẩn bị biểu đồ...', reportAria: 'Báo cáo thí nghiệm RAG và Fine-tuned', localPending: 'Kết quả local đã sẵn sàng. Official RAGAS vẫn đang chạy hoặc có câu chấm lỗi; các metric chưa hoàn tất không được gắn nhãn RAGAS chính thức.',
    output: 'Kết quả nghiên cứu · RBL', comparison: 'So sánh RAG và Fine-tuned', evaluated: 'Đánh giá trên {dataset} bằng cùng một snapshot dữ liệu để bảo đảm công bằng.', exportCsv: 'Xuất CSV', print: 'In / lưu PDF', questions: 'Số câu hỏi', documents: 'Số tài liệu', metricStandard: 'Chuẩn metric', formulaVersion: 'Phiên bản công thức',
    conclusion: 'Kết luận thực nghiệm', keyFindings: 'Những phát hiện chính, không gộp thành một điểm số tùy tiện', partial: 'Báo cáo có kết quả chưa hoàn tất. Các câu lỗi vẫn được hiển thị trong phần tổng hợp và bảng chi tiết.',
    dashboard: '01 · Tổng quan thí nghiệm', dashboardTitle: 'Kết quả trực quan trên cùng snapshot dữ liệu', validSamples: 'Mẫu hợp lệ', quality: 'Chất lượng', speed: 'Tốc độ', comparability: 'Khả năng so sánh', qualityComparison: 'So sánh chất lượng', qualitySubtitle: 'Hai proxy local, theo phần trăm; trục bắt đầu từ 0.', qualityNote: 'Hai chỉ số này cùng dùng tín hiệu token-overlap nên không phải các bằng chứng độc lập.', grounding: 'Độ bám nguồn RAG', groundingSubtitle: 'Chỉ đánh giá cho pipeline có context được truy xuất.', groundingNote: 'Fine-tuned không hiển thị vì không truy xuất tài liệu hoặc tạo evaluation context.', resultsAcross: 'Kết quả trên {count} câu hỏi', resultsSubtitle: 'Mỗi câu được phân loại theo chênh lệch answer-correctness; dưới 2 điểm phần trăm là gần tương đương.', ragBetter: 'RAG tốt hơn', fineBetter: 'Fine-tuned tốt hơn', nearEquivalent: 'Gần tương đương', hasErrors: 'Có lỗi', correctness: 'Độ chính xác theo từng câu', correctnessSubtitle: '{valid} mẫu hợp lệ; {omitted} mẫu thiếu metric hoặc có lỗi bị loại khỏi biểu đồ phân tán.', aboveDiagonal: 'Trên đường chéo: Fine-tuned tốt hơn', belowDiagonal: 'Dưới đường chéo: RAG tốt hơn', responseTime: 'Thời gian phản hồi', responseSubtitle: 'Latency hiệu dụng trung bình mỗi câu; thấp hơn tốt hơn.', insufficientScatter: 'Chưa đủ mẫu cho biểu đồ phân tán', insufficientScatterBody: 'Có {count} mẫu hợp lệ. Cần ít nhất 8 mẫu để thể hiện mối quan hệ có ý nghĩa; dữ liệu vẫn có trong bảng chi tiết.',
    table: '02 · Bảng số liệu', officialRagas: 'Benchmark RAGAS chính thức', localBenchmark: 'Kết quả benchmark local', metric: 'Chỉ số', interpretation: 'Diễn giải', higherBetter: 'Cao hơn tốt hơn', lowerBetter: 'Thấp hơn tốt hơn', viewCalculation: 'Xem cách tính', notApplicable: 'Không áp dụng', noRetrieval: 'Không có context truy xuất', methodologyNote: 'Phương pháp:', methodologyText: 'faithfulness, answer relevancy, context precision và context recall là RAGAS chính thức. Token overlap được hiển thị riêng với nhãn proxy.', tokenOverlap: 'Độ trùng token (proxy)', answerRelevance: 'Mức độ liên quan câu trả lời', faithfulness: 'Tính bám sát nguồn', contextPrecision: 'Độ chính xác context', contextRecall: 'Độ bao phủ context', sourceHit: 'Tỷ lệ trúng tài liệu', pageHit: 'Tỷ lệ trúng trang', refusalAccuracy: 'Độ chính xác từ chối', successfulRate: 'Tỷ lệ chạy thành công', chartData: 'Dữ liệu biểu đồ', model: 'Mô hình', latency: 'Độ trễ', questionClassification: 'Phân loại câu hỏi', question: 'Câu hỏi', difference: 'Chênh lệch', percentagePoints: 'điểm phần trăm', qualityChartAria: 'Biểu đồ cột so sánh ba chỉ số chất lượng giữa RAG và Fine-tuned', groundingChartAria: 'Biểu đồ cột ngang của ba chỉ số bám nguồn RAG', outcomeChartAria: 'Biểu đồ cột xếp chồng phân loại câu hỏi theo kết quả RAG và Fine-tuned', scatterChartAria: 'Biểu đồ phân tán độ chính xác RAG theo trục ngang và Fine-tuned theo trục dọc', latencyChartAria: 'Biểu đồ cột độ trễ trung bình của RAG và Fine-tuned',
    tokenPlain: 'Mức trùng khớp từ khóa với đáp án chuẩn.', answerPlain: 'Câu trả lời có đi đúng trọng tâm câu hỏi hay không.', faithPlain: 'Câu trả lời RAG có được hỗ trợ bởi context truy xuất hay không.', precisionPlain: 'Các context RAG lấy về có tập trung vào bằng chứng hữu ích hay không.', recallPlain: 'RAG đã lấy đủ bằng chứng cần thiết cho ground truth hay chưa.', sourcePlain: 'Citation có trỏ đúng tài liệu mong đợi hay không.', pagePlain: 'Citation có chứa đúng trang mong đợi hay không.', refusalPlain: 'Model có từ chối đúng câu ngoài phạm vi hay không.', tokenFormula: 'Token F1 nội bộ, không phải metric RAGAS.', answerFormula: 'Metric RAGAS chính thức, chấm bởi OpenAI judge với BGE-M3 evaluator embedding.', officialFormula: 'Metric RAGAS chính thức.', sourceFormula: 'Tỷ lệ câu có document ID khớp expected source.', pageFormula: 'Tỷ lệ câu có expected page nằm trong khoảng trang citation.', refusalFormula: 'Tính trên robustness questions được đánh dấu out-of-scope.', latencyPlain: 'Thời gian hiệu dụng trung bình để xử lý một câu hỏi.', successPlain: 'Tỷ lệ câu có kết quả hợp lệ; các lần chạy lỗi vẫn hiển thị.',
    details: '03 · Phân tích từng câu', detailsTitle: 'Chi tiết {count} câu hỏi', search: 'Tìm nội dung câu hỏi...', filter: 'Lọc kết quả', all: 'Tất cả kết quả', error: 'Có lỗi', proxyDelta: 'Chênh lệch proxy {value} điểm %', groundTruth: 'Đáp án chuẩn', ragSources: 'Nguồn RAG', time: 'Thời gian', noData: 'Không có dữ liệu.', noCitation: 'Không ghi nhận citation.', noRows: 'Không có câu phù hợp bộ lọc.',
    methods: '04 · Minh bạch nghiên cứu', methodsTitle: 'Phương pháp và giới hạn', setup: 'Thiết lập benchmark', limitations: 'Giới hạn cần đọc trước khi kết luận', profile: 'Cấu hình', batchSize: 'Kích thước batch', maxInput: 'Input tối đa', maxOutput: 'Output tối đa', fullBenchmark: 'Benchmark đầy đủ', limitDataset: 'Dataset chỉ gồm {count} câu và không đại diện cho mọi tình huống.', limitTruth: 'Ground truth do người xây dựng dataset cung cấp.', limitJudge: 'OpenAI là judge RAGAS; BGE-M3 là evaluator embedding. Token overlap được ghi riêng là proxy.', limitFine: 'Fine-tuned không truy xuất context nên không có citation, context precision/recall và faithfulness theo nguồn.',
    sameSnapshot: 'Cùng snapshot và cấu hình', needsReview: 'Cần xem lại', insufficientData: 'Chưa đủ dữ liệu', faster: '{model} nhanh hơn khoảng {percent}%', qualityDelta: '{model} khớp ground truth cao hơn {points} điểm phần trăm.', qualityTie: 'Hai model có độ chính xác gần tương đương (chênh lệch dưới 2 điểm phần trăm).', groundingConclusion: 'Với RAG, context precision là {precision} và context recall là {recall}. Các chỉ số này phản ánh mức độ chọn đúng nguồn và truy xuất đủ bằng chứng.', useCase: 'RAG phù hợp khi cần truy vết nguồn; Fine-tuned phù hợp cho câu trả lời trực tiếp. Báo cáo này không kết luận model nào luôn tốt hơn.',
  },
  en: {
    headerTitle: 'RBL research report', headerDescription: 'Compare quality, source grounding, and response speed across RAG and Fine-tuned runs.',
    dataset: 'Dataset', ragRun: 'RAG run', fineRun: 'Fine-tuned run', selectDataset: 'Select a dataset', selectRag: 'Select a RAG run', selectFine: 'Select a Fine-tuned run', noDatasets: 'No datasets available', noRag: 'No RAG runs available', noFine: 'No Fine-tuned runs available',
    preparingReport: 'Preparing report...', preparingCharts: 'Preparing charts...', reportAria: 'RAG and Fine-tuned experiment report', localPending: 'Local results are ready. Official RAGAS is still running or some evaluations failed; incomplete metrics are not labelled as official RAGAS.',
    output: 'Research output · RBL', comparison: 'RAG vs Fine-tuned comparison', evaluated: 'Evaluated on {dataset} using the same data snapshot for a fair comparison.', exportCsv: 'Export CSV', print: 'Print / save as PDF', questions: 'Questions', documents: 'Documents', metricStandard: 'Metric standard', formulaVersion: 'Formula version',
    conclusion: 'Experimental conclusion', keyFindings: 'Key findings without collapsing them into one arbitrary score', partial: 'This report has partial results. Failed questions remain visible in the performance summary and detail table.',
    dashboard: '01 · Experiment dashboard', dashboardTitle: 'Visual results on the same dataset snapshot', validSamples: 'Valid samples', quality: 'Quality', speed: 'Speed', comparability: 'Comparability', qualityComparison: 'Quality comparison', qualitySubtitle: 'Two local proxies, in percent; the axis starts at zero.', qualityNote: 'These two figures use the same token-overlap signal, so they are not independent evidence.', grounding: 'RAG source grounding', groundingSubtitle: 'Only evaluated for pipelines with retrieved context.', groundingNote: 'Fine-tuned is not shown because it does not retrieve documents or produce evaluation context.', resultsAcross: 'Results across {count} questions', resultsSubtitle: 'Each question is classified by answer-correctness delta; a difference below 2 percentage points is near equivalent.', ragBetter: 'RAG performs better', fineBetter: 'Fine-tuned performs better', nearEquivalent: 'Near equivalent', hasErrors: 'Has errors', correctness: 'Per-question correctness', correctnessSubtitle: '{valid} valid samples; {omitted} samples with missing metrics or errors are excluded from the scatter plot.', aboveDiagonal: 'Above the diagonal: Fine-tuned performs better', belowDiagonal: 'Below the diagonal: RAG performs better', responseTime: 'Response time', responseSubtitle: 'Average effective latency per question; lower is better.', insufficientScatter: 'Not enough samples for a scatter plot', insufficientScatterBody: 'There are {count} valid samples. At least 8 are needed for a meaningful relationship view; the data remains available in the detail table.',
    table: '02 · Benchmark table', officialRagas: 'Official RAGAS benchmark', localBenchmark: 'Local benchmark results', metric: 'Metric', interpretation: 'Interpretation', higherBetter: 'Higher is better', lowerBetter: 'Lower is better', viewCalculation: 'View calculation', notApplicable: 'Not applicable', noRetrieval: 'No retrieval context', methodologyNote: 'Method:', methodologyText: 'Faithfulness, answer relevancy, context precision, and context recall are official RAGAS metrics. Token overlap is shown separately as a proxy.', tokenOverlap: 'Token overlap (proxy)', answerRelevance: 'Answer relevancy', faithfulness: 'Faithfulness', contextPrecision: 'Context precision', contextRecall: 'Context recall', sourceHit: 'Source hit rate', pageHit: 'Page hit rate', refusalAccuracy: 'Refusal accuracy', successfulRate: 'Successful-run rate', chartData: 'Chart data', model: 'Model', latency: 'Latency', questionClassification: 'Question classification', question: 'Question', difference: 'Difference', percentagePoints: 'percentage points', qualityChartAria: 'Bar chart comparing three quality metrics between RAG and Fine-tuned', groundingChartAria: 'Horizontal bar chart of three RAG source-grounding metrics', outcomeChartAria: 'Stacked bar chart classifying question outcomes for RAG and Fine-tuned', scatterChartAria: 'Scatter plot with RAG correctness on the horizontal axis and Fine-tuned correctness on the vertical axis', latencyChartAria: 'Bar chart of average latency for RAG and Fine-tuned',
    tokenPlain: 'Keyword overlap with the reference answer.', answerPlain: 'Whether the answer addresses the question.', faithPlain: 'Whether the RAG answer is supported by retrieved context.', precisionPlain: 'Whether retrieved RAG context concentrates on useful evidence.', recallPlain: 'Whether RAG retrieved enough evidence for the reference answer.', sourcePlain: 'Whether a citation points to the expected document.', pagePlain: 'Whether a citation contains the expected page.', refusalPlain: 'Whether the model correctly refuses an out-of-scope question.', tokenFormula: 'Internal token F1, not a RAGAS metric.', answerFormula: 'Official RAGAS metric, scored by the OpenAI judge with BGE-M3 evaluator embeddings.', officialFormula: 'Official RAGAS metric.', sourceFormula: 'Rate of questions whose document ID matches the expected source.', pageFormula: 'Rate of questions whose expected page is within the citation page range.', refusalFormula: 'Calculated only on robustness questions marked out-of-scope.', latencyPlain: 'Average effective time to process one question.', successPlain: 'Share of questions with a valid result; failed model runs remain visible.',
    details: '03 · Per-question analysis', detailsTitle: 'Details for {count} questions', search: 'Search question content...', filter: 'Filter results', all: 'All results', error: 'Has errors', proxyDelta: 'Proxy delta {value} pp', groundTruth: 'Ground truth', ragSources: 'RAG sources', time: 'Time', noData: 'No data available.', noCitation: 'No citation recorded.', noRows: 'No questions match this filter.',
    methods: '04 · Research transparency', methodsTitle: 'Methodology and limitations', setup: 'Benchmark setup', limitations: 'Limitations to read before concluding', profile: 'Profile', batchSize: 'Batch size', maxInput: 'Maximum input', maxOutput: 'Maximum output', fullBenchmark: 'Full benchmark', limitDataset: 'The dataset has only {count} questions and does not represent every situation.', limitTruth: 'Ground truth is supplied by the dataset author.', limitJudge: 'OpenAI is the RAGAS judge; BGE-M3 is the evaluator embedding. Token overlap is shown separately as a proxy.', limitFine: 'Fine-tuned does not retrieve context, so it has no citations, context precision/recall, or source faithfulness.',
    sameSnapshot: 'Same snapshot and profile', needsReview: 'Needs review', insufficientData: 'Insufficient data', faster: '{model} faster by about {percent}%', qualityDelta: '{model} matches ground truth better by {points} percentage points.', qualityTie: 'The two models have near-equivalent accuracy (difference below 2 percentage points).', groundingConclusion: 'For RAG, context precision is {precision} and context recall is {recall}. These figures indicate source selection accuracy and evidence coverage.', useCase: 'RAG fits work requiring source traceability; Fine-tuned fits direct answers. This report does not claim either model is universally best.',
  },
}

export function useResearchCopy() {
  const { locale } = useLocale()
  return copy[locale] ?? copy.vi
}

export function interpolate(template, params = {}) {
  return template.replace(/\{(\w+)\}/g, (_, key) => String(params[key] ?? ''))
}
